name       : samba
version    : 4.3.6
release    : 10
source     :
    - https://download.samba.org/pub/samba/stable/samba-4.3.6.tar.gz : 3251eca5b196854e79978f4a92d5fd2b55bd7b0a252a65131a9be02be6754924
license    : GPL-2.0
summary    : Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
description: |
    Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(gnutls)
    - pkgconfig(tdb)
    - pkgconfig(openssl)
    - pkgconfig(libarchive)
    - pkgconfig(avahi-client)
    - libgcrypt-devel
    - cups-devel
    - attr-devel
    - acl-devel
    - pam-devel
    - libcap2-devel
    - libaio-devel
setup      : |
    # TODO: Enable ldap, etc..
    %configure --with-piddir=/run/samba \
               --with-pammodulesdir=/lib/security \
               --with-systemd \
               --enable-fhs \
               --without-ldap \
               --without-ads \
               --bundled-libraries=!tdb
build      : |
    %make
install    : |
    %make_install
    install -m0644 -D $pkgfiles/smb.conf $installdir/etc/samba/smb.conf
    install -m00644 -D $pkgfiles/samba.tmpfiles $installdir/usr/lib/tmpfiles.d/samba.conf
    # cups
    install -D -d -m 00755 $installdir/%libdir%/cups/backend
    ln -sv /usr/bin/smbspool $installdir/%libdir%/cups/backend/smb
    # pam
    install -D -m 00644 $pkgfiles/samba.pam $installdir/etc/pam.d/samba
