name       : samba
version    : 4.2.2
release    : 2
source     :
    - https://download.samba.org/pub/samba/stable/samba-4.2.2.tar.gz : 27d6c69dc3afee38fd28051001d2d4bdae38c567612a9ec6477bb5567e2abc1e
license    : GPL-2.0
summary    : Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
description: |
    Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
builddeps  :
    - pkgconfig(krb5)
    - pkgconfig(gnutls)
    - pkgconfig(tdb)
    - libgcrypt-devel
    - cups-devel
setup      : |
    # TODO: Enable ldap, etc..
    %configure --with-piddir=/run/samba \
               --with-pammodulesdir=/lib/security \
               --with-systemd \
               --enable-fhs \
               --without-ldap \
               --without-ads \
               --bundled-libraries=!tdb
build      : |
    %make
install    : |
    %make_install
    install -m0644 -D $pkgfiles/smb.conf $installdir/etc/samba/smb.conf
