name       : samba
version    : 4.7.8
release    : 39
source     :
    - https://download.samba.org/pub/samba/stable/samba-4.7.8.tar.gz : ca6fca9d7e248bcaa55c54bdcc115eeed10660074da5c54a2b78dd3cccc604de
license    : GPL-2.0
summary    : Provides file and print services to SMB/CIFS clients and Windows networking
    to Linux clients
component  : desktop.core
description: |
    Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients

    Includes a Solus-specific configuration that enables user shares by default (can be disabled).
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(cmocka)
    - pkgconfig(com_err)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(ldb)
    - pkgconfig(libarchive)
    - pkgconfig(libcap)
    - pkgconfig(libtirpc)
    - pkgconfig(libunwind)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - pkgconfig(tevent)
    - acl-devel
    - attr-devel
    - docbook-xml
    - cups-devel
    - libaio-devel
    - gpgme-devel
    - openldap-devel
setup      : |
    # TODO: Enable ldap, etc..
    %configure --with-piddir=/run/samba \
               --with-sockets-dir=/run/samba \
               --with-lockdir=/run/lock \
               --with-pammodulesdir=/lib/security \
               --with-systemd \
               --enable-fhs \
               --with-ads \
               --with-configdir=/usr/share/defaults/samba \
               --bundled-libraries=!cmocka,!tdb,!talloc,!pytalloc-util,!tevent,!popt,!ldb,!pyldb-util \
               --disable-rpath-install
build      : |
    # parallel builds don't work with the macro
    WAF_MAKE=1 python ./buildtools/bin/waf -j%YJOBS% build
install    : |
    %make_install

    # solus-controlled standard smb.conf file which attempts to include /etc/samba/smb.conf
    install -D -m00644 $pkgfiles/smb.conf.solus $installdir/usr/share/defaults/samba/smb.conf
    # no-op solus-specific smb.conf file which explains how the default configuration is set up
    install -D -m00644 $pkgfiles/smb.conf.README $installdir/usr/share/defaults/samba/smb.conf.README
    install -d -m00755 $installdir/etc/samba/
    ln -sv /usr/share/defaults/samba/smb.conf.README $installdir/etc/samba/
    # an example samba smb.conf file with everything commented out
    install -D -m00644 $pkgfiles/smb.conf.example $installdir/usr/share/defaults/samba/smb.conf.example
    # avahi samba service autodiscovery configuration
    install -D -m00644 $pkgfiles/avahi.smb.service $installdir/usr/share/defaults/samba/avahi.smb.service
    install -d -m00755 $installdir/etc/avahi/services
    ln -sv /usr/share/defaults/samba/avahi.smb.service $installdir/etc/avahi/services/smb.service
    # cups
    install -d -m00755 $installdir/%libdir%/cups/backend
    ln -sv /usr/bin/smbspool $installdir/%libdir%/cups/backend/smb
    # pam
    install -D -m00644 $pkgfiles/samba.pam $installdir/etc/pam.d/samba
    # systemd
    install -d -m00755 $installdir/usr/lib/systemd/system
    install -m00644 packaging/systemd/*.service $installdir/usr/lib/systemd/system/.
    install -D -m00644 packaging/systemd/samba.sysconfig $installdir/etc/sysconfig/samba
    # systemd-managed samba-specific directory setup (including a usershares directory)
    install -D -m00644 $pkgfiles/samba.tmpfiles $installdir/%libdir%/tmpfiles.d/samba.conf
    # systemd-managed solus-specific file to create the "sambaguest" system user
    install -D -m00644 $pkgfiles/samba.sysusers $installdir/%libdir%/sysusers.d/samba.conf
    # networkmanager online/offline script
    install -D -m00755 packaging/NetworkManager/30-winbind-systemd $installdir/etc/NetworkManager/dispatcher.d/30-winbind

    rm -rfv $installdir/var/log
    rm -rfv $installdir/run
