name       : samba
version    : 4.6.4
release    : 18
source     :
    - https://download.samba.org/pub/samba/stable/samba-4.6.4.tar.gz : 4ac67329d18e5586dc75db50e23b81c1f6c45a2d5bb9752ea6d90dcca08d9a61
license    : GPL-2.0
summary    : Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
component  : desktop.core
description: |
    Provides file and print services to SMB/CIFS clients and Windows networking to Linux clients
builddeps  :
    - pkgconfig(avahi-client)
    - pkgconfig(com_err)
    - pkgconfig(gnutls)
    - pkgconfig(krb5)
    - pkgconfig(libarchive)
    - pkgconfig(libcap)
    - pkgconfig(libtirpc)
    - pkgconfig(libunwind)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(popt)
    - pkgconfig(tdb)
    - acl-devel
    - attr-devel
    - docbook-xml
    - cups-devel
    - libaio-devel
    - gpgme-devel
    - openldap-devel
setup      : |
    # TODO: Enable ldap, etc..
    %configure --with-piddir=/run/samba \
               --with-sockets-dir=/run/samba \
               --with-pammodulesdir=/lib/security \
               --with-systemd \
               --enable-fhs \
               --with-ads \
               --with-configdir=/etc/samba \
               --bundled-libraries=!tdb,!tirpc
build      : |
    %make
install    : |
    %make_install
    install -m0644 -D $pkgfiles/smb.conf $installdir/etc/samba/smb.conf
    install -m00644 -D $pkgfiles/samba.tmpfiles $installdir/usr/lib/tmpfiles.d/samba.conf
    # cups
    install -D -d -m 00755 $installdir/%libdir%/cups/backend
    ln -sv /usr/bin/smbspool $installdir/%libdir%/cups/backend/smb
    # pam
    install -D -m 00644 $pkgfiles/samba.pam $installdir/etc/pam.d/samba

    # systemd
    install -D -d -m 00755 $installdir/usr/lib/systemd/system
    install -m 0644 $pkgfiles/systemd/*.service $installdir/usr/lib/systemd/system/.
    rm -rfv $installdir/var/{run,lock,log}
